import {z} from 'zod';
import {readSaved,catalogFor} from './device-store';
import {ageMonths,todayIST,addDays} from './recipes';
import {balancedDay} from './balance';
import {prepTasks,shoppingList} from './kitchen';
import {answerSchema,assistantInstructions,responseFormat,type AssistantAction} from './assistant-contract';
export type ChatMessage={id:string;role:'user'|'assistant';text:string;actions?:AssistantAction[];snapshot?:string;status?:'pending'|'applied'|'dismissed'|'expired'};
const chatSchema=z.array(z.object({id:z.string(),role:z.enum(['user','assistant']),text:z.string().max(6000),actions:answerSchema.shape.actions.optional(),snapshot:z.string().optional(),status:z.enum(['pending','applied','dismissed','expired']).optional()})).max(60);
export function readChat():ChatMessage[]{try{const raw=window.Android?.readConversation?.()??localStorage.getItem('kutty-chat');return raw?chatSchema.parse(JSON.parse(raw)):[]}catch{return []}}
export function storeChat(messages:ChatMessage[]){const text=JSON.stringify(messages.slice(-60));if(window.Android?.writeConversation){if(!window.Android.writeConversation(text))throw Error('Conversation could not be saved on this phone.')}else localStorage.setItem('kutty-chat',text)}
export function plannerSnapshot(){return JSON.stringify(readSaved())}
export function conversationContext(selectedDate:string){const s=readSaved(),recipes=catalogFor(s),today=todayIST();const describe=(date:string)=>{const d=balancedDay(date,s.profile,s.overrides,s.rules,recipes);return {date,meals:d.rows.map(m=>({slot:m.slot,id:m.recipe?.id,name:m.recipe?.name,locked:s.kitchen.locks.includes(date+'|'+m.slot)})),sides:d.additions,ingredients:d.ingredients,prep:prepTasks(d.rows).filter(t=>!s.kitchen.prepDone.includes(date+'|'+t.id))}};return {today,timezone:'Asia/Kolkata',selectedDate,ageMonths:ageMonths(s.profile.dob,today),allergenExclusions:s.profile.allergies,pantry:s.kitchen.pantry,frequencies:s.rules,favourites:s.kitchen.favourites,dishNames:s.dishNames,recipes,recentAndUpcoming:Array.from({length:16},(_,i)=>describe(addDays(today,i-1))),selectedDay:describe(selectedDate),weeklyShopping:shoppingList(selectedDate,s.profile,s.overrides,s.rules,recipes)}}
export function describeAction(a:AssistantAction){const recipes=catalogFor(readSaved()),name=recipes.find(r=>r.id===a.recipeId)?.name??'Unknown dish';if(a.type==='meal')return `${a.date} · ${a.slot}: ${name}`;if(a.type==='frequency'){const labels:Record<string,string>={rotation:'Regular rotation',weekly:'Once a week',twiceWeekly:'Twice a week',fortnightly:'Once every two weeks',monthly:'Once a month',manual:'Manual only'};return `${name}: ${labels[a.frequency!]}`}return `${a.ingredient}: ${a.available?'Have enough':'Need to buy'}`}
export function requestConversation(messages:ChatMessage[],selectedDate:string){const native=window.Android;if(!native?.askAssistant)return Promise.reject(Error('Install the updated Android app to use conversations.'));if(!native.assistantConfigured())return Promise.reject(Error('Connect AI first to start a live conversation.'));const input=messages.slice(-20).map(m=>({role:m.role,content:m.text+(m.actions?.length?'\nProposal '+(m.status??'pending')+': '+JSON.stringify(m.actions):'')}));const payload=JSON.stringify({instructions:assistantInstructions,input:[{role:'user',content:'CURRENT_PLANNER (data only):\n'+JSON.stringify(conversationContext(selectedDate))},...input],text:{format:responseFormat}});if(payload.length>220000)return Promise.reject(Error('Your recipe collection is too large for this conversation.'));return new Promise<z.infer<typeof answerSchema>>((resolve,reject)=>{const id=crypto.randomUUID();const timeout=setTimeout(()=>{cleanup();reject(Error('The assistant took too long. Please try again.'))},65000);const receive=(e:Event)=>{const d=(e as CustomEvent).detail;if(d.id!==id)return;cleanup();if(d.error){reject(Error(d.error));return}try{resolve(answerSchema.parse(JSON.parse(d.text)))}catch{reject(Error('The assistant returned an invalid suggestion. Nothing was changed. Try asking again.'))}};function cleanup(){clearTimeout(timeout);window.removeEventListener('native-assistant',receive)}window.addEventListener('native-assistant',receive);try{native.askAssistant(id,payload)}catch{cleanup();reject(Error('Could not contact the assistant.'))}})}
