import {scheduleThrough,type FrequencyRules} from './frequency';
export type Ingredient={name:string,amount:number,unit:string};
export type Recipe={id:string,name:string,tamil:string,slot:string,time:number,ingredients:Ingredient[],steps:string[],allergens:string[],note:string,source:string;prep?:string;custom?:boolean};
const source='';
const make=(id:string,name:string,tamil:string,slot:string,time:number,items:[string,number,string][],steps:string[],allergens:string[]=[],note='') : Recipe=>({id,name,tamil,slot,time,ingredients:items.map(([name,amount,unit])=>({name,amount,unit})),steps,allergens,note,source});
export const recipes:Recipe[]=[
make('idli','Idli','இட்லி','Breakfast',15,[['Fermented idli batter',4,'tbsp'],['Sesame oil',0.25,'tsp']],['Grease idli moulds lightly and add batter.','Steam for 10–12 minutes until fully cooked; rest for 2 minutes.','Crumble and moisten with warm water or dal before serving.'],['Sesame'],'Use properly fermented, refrigerated batter. No whole podi seeds.'),
make('pongal','Ven pongal','வெண் பொங்கல்','Breakfast',30,[['Rice',2,'tbsp'],['Moong dal',1,'tbsp'],['Ghee',0.5,'tsp'],['Ground cumin',0.125,'tsp']],['Wash rice and dal; cook with 250 ml water until very soft.','Stir in ghee and ground cumin; simmer 2 minutes.','Mash to a moist consistency. Omit whole peppercorns and cashews.'],['Milk']),
make('ragi','Ragi kanji','கேழ்வரகு கஞ்சி','Breakfast',12,[['Ragi flour',2,'tbsp'],['Water',150,'ml']],['Whisk flour into cold water with no lumps.','Cook on low heat, stirring, for 8–10 minutes until thoroughly cooked.','Cool to warm; keep spoonable, not watery. Serve with a protein food.'],[],'Fresh cooked kanji, not fermented koozh. No sugar or jaggery.'),
make('dosai','Soft dosai','மென் தோசை','Breakfast',12,[['Fermented dosa batter',4,'tbsp'],['Sesame oil',0.25,'tsp']],['Heat a tawa on medium-low and spread a small thick dosa.','Add a little oil; cover and cook, then turn until cooked through.','Keep soft, not crisp; tear into manageable pieces.'],['Sesame']),
make('aval','Aval upma','அவல் உப்புமா','Breakfast',20,[['Thick aval',3,'tbsp'],['Carrot',1,'tbsp'],['Onion',1,'tbsp'],['Sesame oil',0.25,'tsp']],['Rinse aval and soak until soft, then drain.','Finely mince vegetables; cook in oil with water until mashable.','Add aval with a splash of water; cover until very soft.'],['Sesame']),
make('thinai','Thinai pongal','தினை பொங்கல்','Breakfast',35,[['Thinai millet',2,'tbsp'],['Moong dal',1,'tbsp'],['Ghee',0.5,'tsp'],['Ground cumin',0.125,'tsp']],['Rinse and soak millet for 30 minutes.','Cook with dal and 250 ml water until grains collapse.','Mash well and finish with ghee and ground cumin.'],['Milk']),
make('uthappam','Carrot uthappam','கேரட் ஊத்தப்பம்','Breakfast',18,[['Fermented dosa batter',4,'tbsp'],['Carrot',1,'tbsp'],['Sesame oil',0.25,'tsp']],['Steam finely grated carrot until soft.','Mix into batter and spread a small thick uthappam.','Cook covered on both sides, without a crisp crust.'],['Sesame']),
make('paruppu','Paruppu sadam','பருப்பு சாதம்','Lunch',30,[['Rice',2,'tbsp'],['Toor dal',1,'tbsp'],['Ghee',0.5,'tsp'],['Turmeric',0.0625,'tsp']],['Wash rice and dal. Add turmeric and 250 ml water.','Pressure cook until very soft, following cooker instructions.','Mash together with ghee; add water if dry.'],['Milk']),
make('keerai','Keerai paruppu sadam','கீரை பருப்பு சாதம்','Lunch',30,[['Rice',2,'tbsp'],['Moong dal',1,'tbsp'],['Spinach',2,'tbsp'],['Ghee',0.5,'tsp']],['Wash greens carefully; discard coarse stems and chop finely.','Cook rice and dal until soft. Separately cook greens thoroughly.','Mash together with ghee and enough water to moisten.'],['Milk']),
make('sambar','Vegetable sambar sadam','சாம்பார் சாதம்','Lunch',35,[['Rice',2,'tbsp'],['Toor dal',1,'tbsp'],['Pumpkin',2,'tbsp'],['Tomato',1,'tbsp'],['Ground cumin',0.125,'tsp']],['Cook rice and dal until soft.','Simmer finely chopped pumpkin and tomato with cumin until mashable.','Combine and mash. Keep mild; omit chilli and whole tempering spices.']),
make('curd','Thayir sadam','தயிர் சாதம்','Lunch',25,[['Rice',2,'tbsp'],['Plain pasteurised curd',2,'tbsp']],['Cook rice with plenty of water until soft.','Cool cooked rice promptly to a safe warm temperature.','Mash and stir in fresh pasteurised curd; serve immediately.'],['Milk'],'Do not leave cooked rice or curd rice at room temperature for long.'),
make('carrotdal','Carrot paruppu sadam','கேரட் பருப்பு சாதம்','Lunch',30,[['Rice',2,'tbsp'],['Moong dal',1,'tbsp'],['Carrot',2,'tbsp'],['Ghee',0.5,'tsp']],['Peel and chop carrot. Wash rice and dal.','Cook together with 250 ml water until all ingredients mash easily.','Mash with ghee and serve warm.'],['Milk']),
make('poosani','Poosanikai kootu sadam','பூசணிக்காய் கூட்டு சாதம்','Lunch',30,[['Rice',2,'tbsp'],['Moong dal',1,'tbsp'],['Ash gourd',2,'tbsp'],['Ground cumin',0.125,'tsp']],['Peel ash gourd and remove seeds. Chop finely.','Cook dal and gourd until soft; season with ground cumin.','Serve mashed into well-cooked rice.']),
make('beet','Beetroot paruppu sadam','பீட்ரூட் பருப்பு சாதம்','Lunch',35,[['Rice',2,'tbsp'],['Toor dal',1,'tbsp'],['Beetroot',1,'tbsp'],['Ghee',0.5,'tsp']],['Peel and grate beetroot finely.','Cook rice, dal and beetroot with water until very soft.','Mash with ghee. This is a home-style variation.'],['Milk']),
make('pasi','Paasi payaru mash','பாசிப்பயறு மசியல்','Snack',30,[['Whole green gram',2,'tbsp'],['Ground cumin',0.125,'tsp']],['Soak green gram 6–8 hours, then discard soaking water.','Cook in fresh water until completely soft.','Mash thoroughly so no whole beans remain; add ground cumin.'],[],'Sundal-inspired soft mash; never offer whole beans.'),
make('sweetpotato','Sarkarai valli kizhangu','சர்க்கரைவள்ளிக் கிழங்கு','Snack',25,[['Sweet potato',60,'g']],['Scrub, peel and steam until easily crushed between fingers.','Mash with a little warm water.','Cool and offer a small portion.']),
make('bananaaval','Vazhaipazham aval','வாழைப்பழம் அவல்','Snack',10,[['Thick aval',2,'tbsp'],['Ripe banana',0.5,'small']],['Rinse aval and soak until very soft.','Mash ripe banana smoothly.','Mix together; serve fresh, with no sweetener.']),
make('ulundhu','Ulundhu kanji','உளுந்து கஞ்சி','Snack',30,[['Urad dal',1,'tbsp'],['Rice',1,'tbsp'],['Water',200,'ml']],['Wash dal and rice, then soak for 30 minutes.','Cook with water until completely soft.','Mash or blend coarsely to your child’s chewing ability.']),
make('kondai','Kondakadalai mash','கொண்டைக்கடலை மசியல்','Snack',40,[['Dried chickpeas',2,'tbsp'],['Ground cumin',0.125,'tsp']],['Soak chickpeas 8–12 hours; discard soaking water.','Pressure cook in fresh water until they crush easily.','Remove loose skins and mash thoroughly with cooking water.'],[],'No whole chickpeas, coconut chunks or whole tempering spices.'),
make('pottu','Pottukadalai kanji','பொட்டுக்கடலை கஞ்சி','Snack',12,[['Roasted gram flour',2,'tbsp'],['Water',150,'ml']],['Use finely milled roasted gram flour.','Whisk into water and simmer, stirring for 8–10 minutes.','Cool until warm. Never serve dry powder or whole roasted gram.']),
make('pumpkin','Parangikai masiyal','பரங்கிக்காய் மசியல்','Snack',20,[['Pumpkin',60,'g'],['Moong dal',1,'tbsp']],['Peel pumpkin, remove seeds and chop.','Cook with washed dal and water until soft.','Mash together and serve warm.']),
make('idiyappam','Idiyappam with dal','இடியாப்பம் பருப்பு','Dinner',25,[['Rice flour',3,'tbsp'],['Moong dal',1,'tbsp']],['Mix rice flour with enough hot water to form a soft dough.','Press through an idiyappam mould and steam for 10–12 minutes.','Cook dal until soft. Cut noodles short and moisten thoroughly with dal.']),
make('adai','Soft adai','மென் அடை','Dinner',25,[['Rice',2,'tbsp'],['Toor dal',1,'tbsp'],['Moong dal',1,'tbsp'],['Sesame oil',0.25,'tsp']],['Soak rice and dals for 3–4 hours.','Grind to a smooth batter with water; omit chilli.','Make small thin adai; cook both sides thoroughly but keep soft.'],['Sesame'],'Prep ahead: soak rice and dal.'),
make('sama','Samai vegetable kanji','சாமை காய்கறி கஞ்சி','Dinner',30,[['Samai millet',2,'tbsp'],['Moong dal',1,'tbsp'],['Carrot',1,'tbsp']],['Rinse millet and dal. Finely chop carrot.','Cook together in 250 ml water until grains and vegetables collapse.','Mash until moist and spoonable.']),
make('arisi','Arisi paruppu sadam','அரிசி பருப்பு சாதம்','Dinner',30,[['Rice',2,'tbsp'],['Toor dal',1,'tbsp'],['Tomato',1,'tbsp'],['Onion',1,'tbsp'],['Sesame oil',0.25,'tsp']],['Finely mince onion and tomato; soften with oil and a little water.','Add washed rice and dal with 250 ml water.','Cook until very soft and mash. A mild Kongunadu-style adaptation.'],['Sesame']),
make('ragiadai','Soft ragi adai','கேழ்வரகு அடை','Dinner',20,[['Ragi flour',2,'tbsp'],['Rice flour',1,'tbsp'],['Onion',1,'tbsp'],['Sesame oil',0.25,'tsp']],['Cook minced onion until soft.','Mix flours and onion with water into a soft spreadable dough.','Pat a small thin adai and cook thoroughly on both sides. Moisten before serving.'],['Sesame']),
make('vegupma','Vegetable rava upma','காய்கறி ரவை உப்புமா','Dinner',20,[['Semolina',2,'tbsp'],['Carrot',1,'tbsp'],['Ghee',0.5,'tsp'],['Water',150,'ml']],['Roast semolina lightly without browning.','Cook grated carrot in water until soft.','Slowly stir in semolina; cook fully, keeping it moist with ghee.'],['Wheat','Milk']),
make('kuthirai','Kuthiraivali pongal','குதிரைவாலி பொங்கல்','Dinner',35,[['Kuthiraivali millet',2,'tbsp'],['Moong dal',1,'tbsp'],['Ghee',0.5,'tsp'],['Ground cumin',0.125,'tsp']],['Rinse and soak millet for 30 minutes.','Cook millet and dal with 250 ml water until very soft.','Mash with ghee and ground cumin. Omit nuts and whole pepper.'],['Milk'])];
// Seven lunch choices keep one complete weekly rotation.
recipes[recipes.findIndex(r=>r.id==='carrotdal')]=make('chicken','Kozhi sadam','கோழி சாதம்','Lunch',40,[['Rice',2,'tbsp'],['Boneless chicken',30,'g'],['Carrot',2,'tbsp'],['Tomato',1,'tbsp'],['Sesame oil',0.5,'tsp']],['Finely mince skinless, boneless chicken; check carefully for bone fragments.','Cook chicken, chopped carrot and tomato thoroughly with rice and water. Chicken must reach 74°C throughout.','Shred any fibres finely, mash into moist rice, and cool before serving.'],['Sesame'],'Mild Tamil home-style adaptation; no chilli or whole spices.');
recipes[recipes.findIndex(r=>r.id==='beet')]=make('fish','Meen sadam','மீன் சாதம்','Lunch',30,[['Rice',2,'tbsp'],['Boneless salmon',30,'g'],['Pumpkin',2,'tbsp'],['Ground cumin',0.125,'tsp'],['Sesame oil',0.5,'tsp']],['Cook rice and pumpkin until very soft.','Steam salmon until fully cooked to 63°C; inspect every flake and remove every bone.','Mash fish flakes with rice, pumpkin, cumin and oil.'],['Fish','Sesame'],'Tamil-style mild preparation using lower-mercury salmon; never substitute shark or king mackerel.');
// Original, shortened baby adaptations; source pages describe the traditional base.
recipes.push(
 {...make('ulundhusadam','Ulundhu sadam','','Lunch',35,[['Rice',2,'tbsp'],['Urad dal',0.75,'tbsp'],['Garlic',0.25,'tsp'],['Finely ground coconut',0.5,'tsp'],['Sesame oil',0.25,'tsp']],['Rinse rice and urad dal. Soak for 10 minutes and drain.','Cook with minced garlic, ground coconut and 200 ml water until rice and dal crush easily. Follow the cooker instructions and release pressure safely.','Mix in sesame oil, mash and loosen with warm water. Cool before serving.'],['Sesame'],'Southern Tamil rice-and-urad dish, adapted to a moist baby batch. No jaggery or whole-seed chutney.'),source:'https://gkfooddiary.com/urad-dal-rice-recipe-for-babies-toddlers-and-kids/',prep:'Allow 10 minutes to soak rice and urad dal before cooking.'},
 {...make('ragiidli','Ragi idli','','Breakfast',15,[['Fermented ragi idli batter',4,'tbsp'],['Sesame oil',0.25,'tsp']],['Use prepared, properly fermented ragi, rice and urad batter. The source link explains the larger batter batch.','Lightly oil the moulds. Add batter and steam until completely set, about 10–12 minutes.','Rest briefly, then crumble and moisten with dal or warm water. Check it is soft and cool enough.'],['Sesame'],'Traditional fermented-idli method with ragi. Time excludes batter preparation; omit hard podi toppings.'),source:'https://gkfooddiary.com/ragi-idli-dosa-recipe-for-babies-toddlers-and-kids/',prep:'Prepare ragi idli batter ahead: the source method needs at least 3 hours soaking and roughly 8 hours fermentation. Refrigerate fermented batter until use.'},
 {...make('ragidosai','Soft ragi dosai','','Dinner',15,[['Fermented ragi idli batter',4,'tbsp'],['Sesame oil',0.25,'tsp']],['Loosen prepared fermented ragi batter with a little water.','Spread a small dosa on a medium-low tawa, add oil and cover. Turn and cook the centre completely.','Keep it soft rather than crisp. Tear into manageable pieces and moisten with dal.'],['Sesame'],'Ragi variation of traditional dosai. Time excludes making batter.'),source:'https://gkfooddiary.com/ragi-idli-dosa-recipe-for-babies-toddlers-and-kids/',prep:'Check that properly fermented, refrigerated ragi batter is ready. Making it from scratch needs soaking and fermentation.'}
);
const directSources:Record<string,string>={idiyappam:'https://gkfooddiary.com/idiyappam-for-babies/',keerai:'https://gkfooddiary.com/keerai-sadam-recipe-babies-toddlers/'};
for(const r of recipes)if(directSources[r.id])r.source=directSources[r.id];
export const slots=['Breakfast','Lunch','Snack','Dinner'];
export const todayIST=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const addDays=(day:string,n:number)=>new Date(Date.parse(day+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
export const ageMonths=(dob:string,date:string)=>{const d=new Date(dob+'T00:00:00Z'),t=new Date(date+'T00:00:00Z');return (t.getUTCFullYear()-d.getUTCFullYear())*12+t.getUTCMonth()-d.getUTCMonth()-(t.getUTCDate()<d.getUTCDate()?1:0)};
export type Profile={name:string,dob:string,allergies:string[],anchor:string};
export const defaultProfile:Profile={name:'My little one',dob:todayIST(),allergies:[],anchor:'2026-09-16'};
export function menu(date:string,p:Profile,overrides:Record<string,string>,catalog=recipes,rules:FrequencyRules={}){if(ageMonths(p.dob,date)<12)return [];if(Object.values(rules).some(r=>r.kind!=='rotation'&&r.startsOn<=date))return scheduleThrough(date,p,overrides,catalog,rules)[date]??[];const day=Math.floor((Date.parse(date)-Date.parse(p.anchor))/86400000);return slots.map(slot=>{const pool=catalog.filter(r=>r.slot===slot&&!r.allergens.some(a=>p.allergies.includes(a)));const chosen=overrides[date+'|'+slot];const override=chosen?pool.find(r=>r.id===chosen):undefined;return {slot,recipe:override??pool[((day%pool.length)+pool.length)%pool.length],overridden:!!override,frequency:'rotation' as const}})}
export function ingredientsFor(rows:ReturnType<typeof menu>){const map=new Map<string,Ingredient>();rows.forEach(x=>x.recipe?.ingredients.forEach(i=>{const key=i.name+'|'+i.unit;const old=map.get(key);map.set(key,{...i,amount:(old?.amount??0)+i.amount})}));return [...map.values()]}
export const texture=(months:number)=>months<18?'Mash or offer very soft pieces matched to chewing skills.':months<24?'Offer soft, small pieces as skills allow; mash harder ingredients.':'Offer soft family-food textures; continue cutting and mashing choking hazards.';
