const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:393,height:851},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.testVoice={starts:0,stops:0};window.SpeechRecognition=class {start(){window.testVoice.starts++}stop(){window.testVoice.stops++;this.onresult?.({results:[[{transcript:'shopping list'}]]});this.onend?.()}abort(){}};localStorage.setItem('kutty-samayal-v1',JSON.stringify({version:1,onboarded:true,profile:{name:'Test baby',dob:'2024-01-01',anchor:'2026-09-16',allergies:[]},rules:{},overrides:{},kitchen:{pantry:[],favourites:[],locks:[],prepDone:[]},changes:{},removedIds:[]}))});await page.goto('http://127.0.0.1:4173');await page.getByRole('heading',{name:'Daily menu'}).waitFor();
assert.equal(await page.getByText('Start listening',{exact:true}).count(),0);
const layout=await page.evaluate(()=>{const cards=[...document.querySelectorAll('.meal-grid .meal-card')];return {first:cards[0].getBoundingClientRect().top,secondBottom:cards[1].getBoundingClientRect().bottom,height:innerHeight,overflow:document.body.scrollWidth>innerWidth}});
assert(layout.first<190,'First meal should appear directly below compact date controls');assert(layout.secondBottom<layout.height-70,'First two meal cards should fit above the floating microphone');assert(!layout.overflow);
await page.screenshot({path:'ui-home-compact.png',animations:'disabled'});
await page.setViewportSize({width:320,height:740});assert(!await page.evaluate(()=>document.body.scrollWidth>innerWidth),'Narrow phone must not scroll horizontally');await page.setViewportSize({width:393,height:851});

await page.getByRole('button',{name:'Toggle Sidebar'}).click();await page.getByRole('button',{name:'My dish list',exact:true}).click();await page.getByLabel('Dish names',{exact:true}).fill('Idli\nKeerai sadam\nFamily special');await page.getByRole('button',{name:'Save my dish list'}).click();await page.getByText('Needs recipe · saved, but not scheduled yet').waitFor();assert.equal(await page.getByText('Recipe ready ·',{exact:false}).count(),2);
await page.getByRole('button',{name:'Add ingredients & steps'}).click();assert.equal(await page.getByLabel('Dish name',{exact:true}).inputValue(),'Family special');await page.evaluate(()=>window.dispatchEvent(new Event('native-back',{cancelable:true})));await page.getByRole('dialog').waitFor({state:'detached'});
await page.getByRole('button',{name:'Go back'}).click();await page.getByRole('heading',{name:'Daily menu'}).waitFor();
const carousel=page.getByRole('region',{name:'Sides and snacks carousel'});await carousel.scrollIntoViewIfNeeded();assert(await carousel.evaluate(e=>e.scrollWidth>e.clientWidth));const sizes=await page.evaluate(()=>({meal:document.querySelector('.meal-card').getBoundingClientRect().width,side:document.querySelector('.side-card').getBoundingClientRect().width,overflow:document.body.scrollWidth>innerWidth}));assert(Math.abs(sizes.meal-sizes.side)<2);assert(!sizes.overflow);
await page.screenshot({path:'ui-sides.png'});
await page.getByRole('button',{name:'Toggle Sidebar'}).click();await page.getByRole('button',{name:'Recipe collection',exact:true}).click();await page.getByRole('button',{name:'All (40)',exact:true}).waitFor();assert.equal(await page.locator('.recipe-card').count(),40);await page.locator('.recipe-name').first().click();await page.getByRole('dialog').waitFor();await page.screenshot({path:'ui-detail.png',animations:'disabled'});await page.evaluate(()=>window.dispatchEvent(new Event('native-back',{cancelable:true})));await page.getByRole('dialog').waitFor({state:'detached'});assert.equal(await page.locator('.voice-mic').count(),0);assert.equal(await page.getByText('Talk to Kutty',{exact:true}).count(),0);assert.deepEqual(errors,[]);console.log('PASS compact meals, navigation, dish list, recipes, carousel and no voice UI');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
