import {useEffect,useRef,useState} from 'react';
import {MessageCircle,Send,Volume2,VolumeX,RotateCcw} from 'lucide-react';
import {HandsFree} from './handsfree';
import {Button} from './ui/button';
import {Textarea} from './ui/textarea';
import {localAnswer,describeAction,plannerSnapshot,readChat,requestConversation,storeChat,type ChatMessage} from '../lib/assistant';
export function useConversation({date,save}:{date:string;save:(body:unknown)=>Promise<boolean>}){
 const [messages,setMessages]=useState<ChatMessage[]>(readChat),[busy,setBusy]=useState(false),[input,setInput]=useState(''),[error,setError]=useState(''),[connected,setConnected]=useState(()=>window.Android?.assistantConfigured?.()??false),[readReplies,setReadReplies]=useState(true);
 const history=useRef(messages),working=useRef(false),generation=useRef(0),end=useRef<HTMLDivElement>(null),readRef=useRef(readReplies);readRef.current=readReplies;
 useEffect(()=>{const refresh=()=>setConnected(window.Android?.assistantConfigured?.()??false);window.addEventListener('native-ai-config',refresh);return()=>window.removeEventListener('native-ai-config',refresh)},[]);
 useEffect(()=>{const refresh=()=>{if(!working.current){const rows=readChat();history.current=rows;setMessages(rows)}};window.addEventListener('native-resume',refresh);return()=>window.removeEventListener('native-resume',refresh)},[]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest',behavior:'smooth'})},[messages,busy]);
 function update(rows:ChatMessage[]){history.current=rows.slice(-60);setMessages(history.current);try{storeChat(history.current)}catch(e){setError((e as Error).message)}}
 function speak(text:string){if(!readRef.current||document.visibilityState!=='visible')return;window.speechSynthesis?.cancel();const utterance=new SpeechSynthesisUtterance(text.slice(0,3500));utterance.lang='en-IN';utterance.rate=.95;window.speechSynthesis?.speak(utterance)}
 function pending(){const m=history.current.at(-1);return m?.role==='assistant'&&m.status==='pending'&&m.actions?.length?m:undefined}
 async function approve(message:ChatMessage){if(working.current)return;working.current=true;setBusy(true);setError('');try{const ok=await save({type:'assistantApply',actions:message.actions,snapshot:message.snapshot});if(ok){const text='Done. Your menu, shopping list and evening reminder are updated.';update([...history.current.map(m=>m.id===message.id?{...m,status:'applied' as const}:m),{id:crypto.randomUUID(),role:'assistant',text}]);speak(text)}else{setError('The proposal could not be applied. Check the planner message above, or ask for an updated suggestion.')}}finally{working.current=false;setBusy(false)}}
 function dismiss(message:ChatMessage){update(history.current.map(m=>m.id===message.id?{...m,status:'dismissed' as const}:m));speak('Okay. I have kept your current plan.')}
 async function send(raw:string){if(JSON.parse(window.Android?.handsfreeStatus?.()??'{"active":false}').active){setError('Stop the hands-free session before typing here.');return}const text=raw.trim();if(!text||working.current)return;if(text.length>3000){setError('Please keep each message under 3,000 characters.');return}window.speechSynthesis?.cancel();const proposal=pending();const simple=text.toLowerCase().replace(/[.!?]/g,'').trim();if(proposal&&/^(yes|yes please|confirm|apply changes|go ahead|do it)$/.test(simple)){await approve(proposal);setInput('');return}if(proposal&&/^(no|no thanks|cancel|keep current plan)$/.test(simple)){dismiss(proposal);setInput('');return}
 const local=localAnswer(text);if(!local&&!window.Android?.assistantConfigured?.()){setError('Menu and prep questions work on this phone. Connect AI for open-ended conversation.');return}working.current=true;setBusy(true);setError('');setInput('');const rows:ChatMessage[]=[...history.current.map(m=>m.status==='pending'?{...m,status:'expired' as const}:m),{id:crypto.randomUUID(),role:'user',text}];update(rows);const turn=++generation.current;
 try{const snapshot=plannerSnapshot();const answer=local??await requestConversation(rows,date);if(turn!==generation.current)return;const reply:ChatMessage={id:crypto.randomUUID(),role:'assistant',text:answer.reply,actions:answer.actions,snapshot:answer.actions.length?snapshot:undefined,status:answer.actions.length?'pending':undefined};update([...history.current,reply]);speak(answer.reply)}catch(e){if(turn===generation.current)setError((e as Error).message)}finally{working.current=false;setBusy(false)}}
 function clear(){if(working.current)return;generation.current++;window.speechSynthesis?.cancel();update([]);setError('');setInput('')}
 const panel=<section className="conversation"><HandsFree/><div className="chat-toolbar"><span className="count-pill"><MessageCircle size={15}/>{connected?'Low-data AI ready':'On-phone help ready'}</span><Button variant="ghost" onClick={()=>{setReadReplies(v=>!v);window.speechSynthesis?.cancel()}} aria-pressed={readReplies}>{readReplies?<Volume2 size={18}/>:<VolumeX size={18}/>}Read replies</Button><Button variant="ghost" disabled={busy} onClick={clear}><RotateCcw size={16}/>New chat</Button></div>
 {!connected&&<section className="panel chat-connect"><h2>Connect your conversation assistant</h2><p>Menu and tonight’s prep questions work without AI charges. For natural follow-ups and suggestions, connect your OpenAI API account once. Only conversational requests use separately billed AI; planning and reminders run on your phone.</p><Button onClick={()=>window.Android?.configureAssistant?.()}>Connect AI</Button><p className="small-note">Sending a message shares the conversation, age in months, allergen exclusions and planner context with OpenAI. Your baby’s name and birth date are not automatically included.</p></section>}
 {!messages.length&&<div className="chat-welcome"><h2>Let’s work out the next meal.</h2><p>Type below or hold the microphone. I’ll remember the recent conversation, so you can say “change that” or “what do I need tonight?”.</p><div className="chat-prompts">{['What can I make tomorrow?','We had idli today. Suggest something else.','What should I prepare tonight?'].map(text=><Button key={text} variant="outline" disabled={busy} onClick={()=>send(text)}>{text}</Button>)}</div></div>}
 <div className="chat-messages" role="log" aria-label="Conversation">{messages.map(m=><article className={'chat-bubble '+m.role} key={m.id}><span className="chat-author">{m.role==='user'?'You':'Kutty'}</span><p>{m.text}</p>{!!m.actions?.length&&<div className="chat-proposal"><b>{m.status==='applied'?'Applied changes':m.status==='pending'?'Proposed changes':'Earlier proposal · '+m.status}</b><ul>{m.actions.map((a,i)=><li key={i}>{describeAction(a)}</li>)}</ul>{m.status==='pending'&&<><p>Meal choices override automatic rotation for those dates. Review them, then say “yes” or tap Apply changes.</p><div className="dialog-tools"><Button disabled={busy} onClick={()=>approve(m)}>Apply changes</Button><Button variant="outline" disabled={busy} onClick={()=>dismiss(m)}>Keep current plan</Button></div></>}</div>}</article>)}{busy&&<p role="status" className="chat-thinking">Kutty is working on your request…</p>}<div ref={end}/></div>
 {error&&<p className="message error" role="alert">{error}</p>}<form className="chat-compose" onSubmit={e=>{e.preventDefault();send(input)}}><Textarea aria-label="Message Kutty" value={input} maxLength={3000} onChange={e=>setInput(e.target.value)} placeholder="Ask Kutty about a meal…" rows={2}/><Button type="submit" aria-label="Send message" disabled={busy||!input.trim()}><Send size={19}/></Button></form><div className="chat-footer"><span>Everyday menu and prep answers use no AI tokens. AI receives up to 8 recent messages and compact planner details. New chat clears history.</span><Button variant="ghost" disabled={busy} onClick={()=>window.Android?.configureAssistant?.()}>AI connection</Button></div></section>;
 return {panel,send,busy};
}
