import {useState} from 'react';
import {Button} from './ui/button';
import {Textarea} from './ui/textarea';
import {NativeSelect,NativeSelectOption} from './ui/native-select';
import {frequencyOptions,type FrequencyRules} from '../lib/frequency';
import {matchDish,parseDishNames} from '../lib/dish-names';
import type {Recipe} from '../lib/recipes';
export function DishList({names,recipes,rules,busy,save,open,add}:{names:string[];recipes:Recipe[];rules:FrequencyRules;busy:boolean;save:(body:unknown)=>Promise<boolean>;open:(r:Recipe)=>void;add:(name:string)=>void}){
 const [text,setText]=useState(''),[error,setError]=useState('');
 async function submit(){const added=parseDishNames(text);if(!added.length){setError('Enter at least one dish name.');return}if(added.some(n=>n.length<2||n.length>100)){setError('Each name must have 2–100 characters.');return}const combined=parseDishNames([...names,...added].join('\n'));if(combined.length>200){setError('Keep up to 200 names in your list.');return}setError('');if(await save({type:'dishNames',names:combined}))setText('')}
 return <><section className="panel dish-entry"><h2>What would you like to serve?</h2><p>Enter one dish per line, or separate names with commas. Your list stays saved on this phone.</p><label htmlFor="dish-names">Dish names</label><Textarea id="dish-names" rows={5} value={text} onChange={e=>setText(e.target.value)} placeholder={'Idli\nVen pongal\nKeerai sadam\nYour family dish'}/>{error&&<p role="alert">{error}</p>}<Button disabled={busy||!text.trim()} onClick={submit}>Save my dish list</Button></section><div className="info-banner"><p>Known recipes already take part in rotation; choose weekly, monthly or another frequency below. New names stay under “Needs recipe” until you add ingredients and steps. This list does not exclude other dishes from your planner. Name-only recipe generation is not connected.</p></div><h2>{names.length} saved dish names</h2><div className="dish-list">{names.map(name=>{const r=matchDish(name,recipes);return <article className="panel" key={name}><div className="section-heading"><h3>{name}</h3><Button variant="ghost" disabled={busy} aria-label={'Remove '+name+' from my list'} onClick={()=>save({type:'dishNames',names:names.filter(n=>n!==name)})}>Remove from list</Button></div>{r?<><p className="muted">Recipe ready · {r.name} · {r.slot}</p><label>How often?<NativeSelect value={rules[r.id]?.kind??'rotation'} disabled={busy} onChange={e=>save({type:'frequency',recipeId:r.id,kind:e.target.value})}>{frequencyOptions.map(([value,label])=><NativeSelectOption key={value} value={value}>{label}</NativeSelectOption>)}</NativeSelect></label><Button variant="outline" onClick={()=>open(r)}>View or tweak recipe</Button></>:<><p className="muted">Needs recipe · saved, but not scheduled yet</p><Button onClick={()=>add(name)}>Add ingredients &amp; steps</Button></>}</article>})}</div>{!!names.length&&<p className="small-note">“Remove from list” only removes the saved name. To stop a recipe appearing, set it to Manual only or remove the dish from Recipe collection.</p>}</>;
}
