import {useEffect,useState} from 'react';
import {Mic} from 'lucide-react';
import {Button} from './ui/button';
type Status={active:boolean;remainingSeconds:number;phase:string;lastReply?:string;lastError?:string;lastWake?:number;micReady?:boolean;micLevel?:number;micSilenced?:boolean};
export function HandsFree(){
 const [status,setStatus]=useState<Status>({active:false,remainingSeconds:0,phase:'Off'});
 useEffect(()=>{const refresh=()=>{try{setStatus(JSON.parse(window.Android?.handsfreeStatus?.()??'{"active":false,"remainingSeconds":0,"phase":"Off"}'))}catch{}};refresh();const timer=setInterval(refresh,300);return()=>clearInterval(timer)},[]);
 return <section className="panel"><h2>Hands-free cooking</h2><p>Start a 60-minute session, then say “Hey Kutty”, wait for the beep and ask your question. Works with the screen locked. Say “stop” to end the session.</p><p className="small-note">Wake words stay on this phone. After the beep, your phone’s speech service may process audio online. AI uses the same small conversation context. Review and apply proposed changes in the app.</p>{!status.active&&status.phase!=='Off'&&<p role="status">{status.phase}</p>}{status.active?<>{status.lastReply&&<p>{status.lastReply}</p>}<p role="status">{status.phase} · {Math.ceil(status.remainingSeconds/60)} minutes left</p><p className="small-note">{status.micSilenced?'Android has silenced the microphone. Check microphone privacy settings and other recording apps.':status.micReady?'Microphone receiving audio':'Microphone paused or starting'}</p><meter aria-label="Microphone sound level" min={0} max={0.08} value={status.micLevel??0} style={{width:'100%'}}/>{!!status.lastWake&&<p className="small-note">Wake word detected at {new Date(status.lastWake).toLocaleTimeString('en-IN')}</p>}{status.lastError&&<p role="alert">{status.lastError}</p>}<div className="dialog-tools"><Button onClick={()=>window.Android?.stopHandsfree?.()}>Stop hands-free</Button><Button variant="outline" disabled={!['Say Hey Kutty','Starting microphone'].includes(status.phase)} onClick={()=>window.Android?.handsfreeSpeakNow?.()}><Mic size={18}/>Ask now</Button></div></>:<Button disabled={!window.Android?.startHandsfree} onClick={()=>window.Android?.startHandsfree?.()}>Start 60-minute session</Button>}</section>;
}
