import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {exportBackup,importBackup,refreshReminders} from '@/lib/device-store';
export function PhoneSettings({reload}:{reload:()=>void}){
 const [status,setStatus]=useState<Record<string,any>>({}),[message,setMessage]=useState(''),[pending,setPending]=useState('');
 const refresh=()=>{if(window.Android)setStatus(JSON.parse(window.Android.notificationStatus()))};
 useEffect(()=>{refresh();const resume=()=>refresh();const imported=(e:Event)=>{const d=(e as CustomEvent).detail;if(d.error)setMessage(d.error);else setPending(d.text)};const result=(e:Event)=>setMessage((e as CustomEvent).detail.message);window.addEventListener('native-resume',resume);window.addEventListener('native-import',imported);window.addEventListener('native-message',result);return()=>{window.removeEventListener('native-resume',resume);window.removeEventListener('native-import',imported);window.removeEventListener('native-message',result)}},[]);
 return <><section className="panel"><h2>Tomorrow’s menu at 6 PM IST</h2><p>Phone reminders include the next day’s meals, ingredient quantities and preparation jobs. They work without opening the app each evening.</p><p><b>Notifications:</b> {status.enabled?'Allowed':'Not enabled'} · <b>Precise timing:</b> {status.exact?'Allowed':'Android may delay delivery'}</p>{status.next&&<p>Next reminder: {new Date(status.next).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p>}<div className="dialog-tools"><Button onClick={()=>{window.Android?.enableNotifications();refresh()}}>Enable notifications</Button><Button variant="outline" onClick={()=>window.Android?.openAlarmSettings()}>Allow precise reminders</Button><Button variant="outline" onClick={()=>window.Android?.testNotification()}>Test notification</Button><Button variant="outline" onClick={()=>{try{refreshReminders();refresh();setMessage('Reminder schedule refreshed.')}catch(e){setMessage((e as Error).message)}}}>Refresh reminders</Button><Button variant="ghost" onClick={()=>window.Android?.openNotificationSettings()}>Phone notification settings</Button></div><p className="small-note">The time stays at 6 PM India time even when travelling. Android battery restrictions or force-stopping the app can delay or stop notifications; reopen it after force-stop. Each opening refreshes roughly a year of reminders. No ChatGPT login is needed.</p></section><section className="panel"><h2>Your recipes stay on this phone</h2><p>Your edits, pantry and menu choices work offline. This version does not automatically sync with the earlier website or its ChatGPT reminder.</p><div className="dialog-tools"><Button onClick={()=>{try{window.Android?.exportBackup(exportBackup())}catch(e){setMessage((e as Error).message)}}}>Save backup file</Button><Button variant="outline" onClick={()=>window.Android?.importBackup()}>Import backup</Button></div>{pending&&<div className="message"><p>Replace this phone’s saved dishes and preferences with the selected backup? Save a backup first if you need the current version.</p><Button onClick={()=>{try{importBackup(pending);setPending('');setMessage('Backup imported.');reload();refresh()}catch(e){setMessage((e as Error).message)}}}>Replace with backup</Button><Button variant="ghost" onClick={()=>setPending('')}>Cancel</Button></div>}<p className="small-note">Uninstalling the app removes local data. Keep a backup before switching phones or reinstalling.</p></section>{message&&<p className="message" role="status">{message}</p>}</>;
}
