'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,MicOff} from 'lucide-react';
import {Button} from '@/components/ui/button';
type Recognition={lang:string;continuous:boolean;interimResults:boolean;onresult:((e:{results:{length:number;[n:number]:{isFinal:boolean;0:{transcript:string}}};resultIndex:number})=>void)|null;onend:(()=>void)|null;onerror:((e:{error:string})=>void)|null;start:()=>void;abort:()=>void};
export function useVoiceControl({onCommand}:{onCommand:(command:string)=>string}){
 const [supported,setSupported]=useState(false),[active,setActive]=useState(false),[status,setStatus]=useState(''),[heard,setHeard]=useState('');
 const recognition=useRef<Recognition|null>(null);const wanted=useRef(false);const handler=useRef(onCommand);handler.current=onCommand;
 useEffect(()=>{const w=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const C=w.SpeechRecognition??w.webkitSpeechRecognition;if(!C)return;setSupported(true);const rec=new C();recognition.current=rec;rec.lang='en-IN';rec.continuous=true;rec.interimResults=false;
 rec.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal){const text=e.results[i][0].transcript.trim();setHeard(text);if(/^(stop listening|microphone off)[.!?]?$/i.test(text)){wanted.current=false;rec.abort();setActive(false);setStatus('Microphone off.');return;}if(window.speechSynthesis?.speaking){setStatus('Wait for read-aloud to finish, then say your command.');return}setStatus(handler.current(text));}};
 rec.onerror=e=>{wanted.current=false;setActive(false);setStatus(e.error==='not-allowed'?'Microphone access was denied. Allow it in your phone settings to use voice.':'Voice stopped ('+e.error+'). Try starting again; an internet connection may be needed.');};
 rec.onend=()=>{if(wanted.current&&document.visibilityState==='visible'){try{rec.start()}catch{wanted.current=false;setActive(false);setStatus('Tap Start listening to resume.')}}else setActive(false)};
 const hide=()=>{if(document.visibilityState!=='visible'){wanted.current=false;rec.abort();setActive(false)}};document.addEventListener('visibilitychange',hide);return()=>{wanted.current=false;rec.abort();document.removeEventListener('visibilitychange',hide)};
 },[]);
 return <div className="voice-panel"><Button variant={active?'default':'outline'} disabled={!supported} onClick={()=>{if(active){wanted.current=false;recognition.current?.abort();setActive(false);setStatus('Microphone off.')}else{window.speechSynthesis?.cancel();wanted.current=true;try{recognition.current?.start();setActive(true);setStatus('Listening for English commands…')}catch{wanted.current=false;setStatus('Could not start. Try again.')}}}}>{active?<MicOff size={17}/>:<Mic size={17}/>} {active?'Stop listening':'Start listening'}</Button><p role="status">{status||(!supported?'An Android speech service is unavailable. Enable or install Speech Services by Google.':'Tap once and allow the microphone. Keep the app open.')}</p>{heard&&<small>Heard: “{heard}”</small>}<details><summary>Voice commands & privacy</summary><p>Say “tomorrow’s menu”, “shopping list”, “open idli”, “cook breakfast”, “next step”, “previous step”, “repeat step”, “read ingredients”, “close recipe” or “stop listening”. Voice does not save or delete dishes.</p><p>Android may send audio to its speech service. Recognition varies by device and connection. No wake word, background or locked-screen listening. Commands spoken while read-aloud is playing are ignored to avoid the app hearing itself.</p></details></div>
}
