'use client';
import {useEffect,useMemo,useState,useRef} from 'react';
import {BookOpen,CalendarDays,ChefHat,Check,ChevronLeft,ChevronRight,Clock,Heart,Home as HomeIcon,Leaf,LockKeyhole,LockKeyholeOpen,PackageCheck,RefreshCw,Search,ShoppingBasket,Sun,Moon,Utensils,Users,Volume2,Square,Zap,Bell,ArrowRight,UserRound,X} from 'lucide-react';
import {Sidebar,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarHeader,SidebarInset,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {useConversation} from '@/components/conversation';
import {DishList} from '@/components/dish-list';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {recipes as baseRecipes,defaultProfile,todayIST,addDays,ageMonths,texture,type Recipe,type Profile} from '@/lib/recipes';
import {frequencyOptions,frequencyLabel,type FrequencyRules} from '@/lib/frequency';
import {balancedDay,reviewWeek} from '@/lib/balance';
import {emptyKitchen,namesFor,prepTasks,shoppingList,stockMatch,suggestDay,familyGuide,type KitchenState} from '@/lib/kitchen';
import {RecipeEditor} from '@/components/recipe-editor';
import {useVoiceControl} from '@/components/voice-control';
import {allergens} from '@/lib/catalog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {localRequest,refreshReminders} from '@/lib/device-store';
import {PhoneSettings} from '@/components/phone-settings';
type View='home'|'week'|'recipes'|'pantry'|'shopping'|'prep'|'busy'|'family'|'cook'|'favourites'|'profile'|'phone'|'dishes'|'assistant';
type Data={profile:Profile;rules:FrequencyRules;overrides:Record<string,string>;kitchen:KitchenState;recipes:Recipe[];removed:Recipe[];onboarded?:boolean;dishNames:string[]};
const initial:Data={profile:defaultProfile,rules:{},overrides:{},kitchen:emptyKitchen,recipes:baseRecipes,removed:[],dishNames:[]};
const nav=[{id:'home',name:'My day',icon:HomeIcon},{id:'week',name:'Week planner',icon:CalendarDays},{id:'recipes',name:'Recipe collection',icon:BookOpen},{id:'assistant',name:'Talk to Kutty',icon:Volume2},{id:'dishes',name:'My dish list',icon:Utensils},{id:'pantry',name:'My pantry',icon:PackageCheck},{id:'shopping',name:'Shopping list',icon:ShoppingBasket},{id:'prep',name:'Prepare tonight',icon:Moon},{id:'busy',name:'Busy day',icon:Zap},{id:'family',name:'Family meals',icon:Users},{id:'cook',name:'Cooking view',icon:ChefHat},{id:'favourites',name:'Favourites & locks',icon:Heart},{id:'profile',name:'My baby',icon:UserRound},{id:'phone',name:'My phone',icon:Bell}] as const;
const headings:Record<View,[string,string]>={assistant:['Talk to Kutty','A conversation about your little one’s meals.'],dishes:['Your family’s dish list','Paste dish names, then choose how often to serve them.'],phone:['Your phone, your kitchen','Reminders, voice and saved recipes.'],home:['A happy little mealtime','A little planning, a little less rush.'],week:['A week of good food','Seven days, planned around your little one.'],recipes:['Little favourites start here','Traditional Tamil home cooking, with baby-ready preparation.'],pantry:['What’s in your kitchen?','Check what you have. We’ll help you use it.'],shopping:['One list. One less job.','Ingredients for all seven days, added together.'],prep:['A little prep tonight','Make tomorrow’s mealtimes easier.'],busy:['Less time in the kitchen','Quick swaps for a busy day.'],family:['One kitchen. Everyone fed.','A shared family base, finished for little eaters.'],cook:['Your hands-free helper','Big instructions and English read-aloud, when supported.'],favourites:['Keep the meals you love','Save favourites and lock them into a particular day.'],profile:['Growing together','A few details to keep meals suitable.']};
const nice=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',weekday:'short',day:'numeric',month:'short'});
const amount=(n:number)=>Number(n.toFixed(3)).toString();
function SideNav({view,go,name}:{view:View;go:(v:View)=>void;name:string}){const {setOpenMobile}=useSidebar();return <Sidebar className="kid-sidebar"><SidebarHeader><a className="brand" href="#"><span className="brand-mark"><Utensils size={24}/></span><span>Kutty Samayal<small>Little plates, big love</small></span></a><Button className="mobile-menu-close" variant="ghost" onClick={()=>setOpenMobile(false)}><X/>Close menu</Button></SidebarHeader><SidebarContent>{[nav.slice(0,3),nav.slice(3,10),nav.slice(10)].map((group,i)=><SidebarGroup key={i}><SidebarGroupLabel>{['DAILY PLANS','YOUR KITCHEN HELPERS','PERSONAL'][i]}</SidebarGroupLabel><SidebarMenu>{group.map(item=><SidebarMenuItem key={item.id}><SidebarMenuButton isActive={view===item.id} onClick={()=>{go(item.id);setOpenMobile(false)}}><item.icon/><span>{item.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup>)}</SidebarContent><SidebarFooter><div className="sidebar-reminder"><Bell size={19}/><div><b>A little nudge at 6 PM</b><small>Tomorrow’s menu on your phone<br/>India time</small></div></div><p className="sidebar-child">Made for {name}</p></SidebarFooter></Sidebar>}
export default function App(){return <SidebarProvider><KitchenApp/></SidebarProvider>}
function KitchenApp(){
 const [data,setData]=useState<Data>(initial),[draft,setDraft]=useState<Profile>(defaultProfile),[view,setView]=useState<View>('home'),[date,setDate]=useState(''),[ready,setReady]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[stockSearch,setStockSearch]=useState(''),[missingOnly,setMissingOnly]=useState(true),[selected,setSelected]=useState<Recipe|null>(null),[detailMode,setDetailMode]=useState<'recipe'|'cook'|'family'>('recipe'),[swap,setSwap]=useState<string|null>(null),[step,setStep]=useState(0),[voice,setVoice]=useState(false),[speaking,setSpeaking]=useState(false);
 const [editorName,setEditorName]=useState(''),[mealFilter,setMealFilter]=useState('All');
 const trail=useRef<{view:View,date:string,search:string,scroll:number}[]>([]);const [depth,setDepth]=useState(0);const {openMobile,setOpenMobile}=useSidebar();
 const [editing,setEditing]=useState<Recipe|null|undefined>(undefined),[removing,setRemoving]=useState<Recipe|null>(null);
 const {profile,rules,overrides,kitchen,recipes}=data;const ingredientNames=namesFor(recipes);const dayDate=date||todayIST();const tomorrow=addDays(todayIST(),1);const months=ageMonths(profile.dob,todayIST());
 async function load(){setError('');try{const r=await localRequest('GET');const json=await r.json() as Data&{error?:string};if(!r.ok)throw Error(json.error||'Could not load your planner');setData({...json,kitchen:json.kitchen??emptyKitchen});setDraft(json.profile);if(!json.onboarded)setView('profile');setSelected(old=>old?json.recipes.find(r=>r.id===old.id)??null:null);setReady(true);return true}catch(e){setError((e as Error).message);return false}}
 useEffect(()=>{setDate(todayIST());load().then(()=>{try{refreshReminders()}catch(e){setError((e as Error).message)}});setVoice('speechSynthesis' in window);return()=>{if('speechSynthesis' in window)window.speechSynthesis.cancel()}},[]);
 async function save(body:unknown){setSaving(true);setNotice('');setError('');try{const r=await localRequest('POST',body as Record<string,any>);const result=await r.json() as {error?:string;message?:string};if(!r.ok)throw Error(result.error||'Could not save');if(!await load())throw Error('Saved, but the refreshed plan could not be loaded. Please retry.');setNotice(result.message||'Saved');return true}catch(e){setError((e as Error).message);return false}finally{setSaving(false)}}
 useEffect(()=>{window.Android?.keepAwake(!!selected&&detailMode==='cook');return()=>window.Android?.keepAwake(false)},[selected,detailMode]);
 useEffect(()=>{const openNotice=(e:Event)=>{const d=(e as CustomEvent).detail;if(d.date){setDate(d.date);setView('home')}};const resume=()=>{try{refreshReminders()}catch{} };window.addEventListener('native-menu',openNotice);window.addEventListener('native-resume',resume);return()=>{window.removeEventListener('native-menu',openNotice);window.removeEventListener('native-resume',resume)}},[]);
 const flag=(kind:'pantry'|'favourite'|'prep',key:string,checked:boolean)=>save({type:'flag',kind,key,checked});
 const go=(next:View)=>{if(next===view)return;trail.current.push({view,date:dayDate,search,scroll:window.scrollY});setDepth(trail.current.length);setView(next);setSearch('');setNotice('');if(next==='prep')setDate(tomorrow);window.scrollTo(0,0)};
 function back(){if(saving)return true;if(removing){setRemoving(null);return true}if(editing!==undefined){setEditing(undefined);return true}if(swap){setSwap(null);return true}if(selected){stopVoice();setSelected(null);return true}if(openMobile){setOpenMobile(false);return true}const prev=trail.current.pop();if(prev){setDepth(trail.current.length);setView(prev.view);setDate(prev.date);setSearch(prev.search);setNotice('');requestAnimationFrame(()=>window.scrollTo(0,prev.scroll));return true}if(view!=='home'&&data.onboarded){setView('home');return true}return false}
 useEffect(()=>{const onBack=(e:Event)=>{if(back())e.preventDefault()};window.addEventListener('native-back',onBack);return()=>window.removeEventListener('native-back',onBack)});

 const open=(r:Recipe,mode:'recipe'|'cook'|'family'='recipe')=>{stopVoice();setSelected(r);setDetailMode(mode);setStep(0);setError('');setNotice('')};
 function stopVoice(){if(typeof window!=='undefined'&&'speechSynthesis' in window)window.speechSynthesis.cancel();setSpeaking(false)}
 function readAloud(){if(!selected||!voice)return;stopVoice();const message=new SpeechSynthesisUtterance(selected.name+'. '+selected.steps.join(' '));const voices=window.speechSynthesis.getVoices();const english=voices.find(v=>v.lang==='en-IN')??voices.find(v=>v.lang.startsWith('en'));if(english)message.voice=english;message.lang=english?.lang??'en-IN';message.rate=.86;message.onend=()=>setSpeaking(false);message.onerror=()=>{setSpeaking(false);setError('Read-aloud is unavailable on this device. The written steps are below.')};setSpeaking(true);window.speechSynthesis.speak(message)}
 const day=useMemo(()=>balancedDay(dayDate,profile,overrides,rules,recipes),[dayDate,profile,overrides,rules,recipes]);
 const nextDay=useMemo(()=>balancedDay(tomorrow,profile,overrides,rules,recipes),[tomorrow,profile,overrides,rules,recipes]);
 const shopping=useMemo(()=>shoppingList(dayDate,profile,overrides,rules,recipes),[dayDate,profile,overrides,rules,recipes]);
 const pendingTomorrow=prepTasks(nextDay.rows).filter(t=>!kitchen.prepDone.includes(tomorrow+'|'+t.id));
 const conversation=useConversation({date:dayDate,save});
 const voicePanel=useVoiceControl({onCommand:command=>{
 if(view==='assistant'){void conversation.send(command);return 'Message sent to Kutty.'}
 const c=command.toLowerCase().replace(/[’']/g,'').replace(/[.!?]/g,'').trim();
 const say=(text:string)=>{if('speechSynthesis' in window){stopVoice();const u=new SpeechSynthesisUtterance(text);u.lang='en-IN';u.rate=.9;window.speechSynthesis.speak(u)}};
 if(c.includes('tomorrow')&&c.includes('menu')){setSelected(null);setDate(tomorrow);go('home');say(nextDay.rows.map(m=>m.slot+': '+(m.recipe?.name??'No suitable dish')).join('. '));return 'Tomorrow’s menu opened.'}
 if(c==='shopping list'||c==='open shopping list'){setSelected(null);go('shopping');return 'Shopping list opened.'}
 if(c==='close recipe'){stopVoice();setSelected(null);return 'Recipe closed.'}
 if(c==='next step'||c==='previous step'){if(!selected)return 'Open a recipe first.';setDetailMode('cook');const next=Math.max(0,Math.min(selected.steps.length-1,step+(c==='next step'?1:-1)));setStep(next);say(selected.steps[next]);return 'Step '+(next+1);}
 if(c==='repeat step'||c==='read ingredients'){if(!selected)return 'Open a recipe first.';say(c==='repeat step'?selected.steps[step]:selected.ingredients.map(i=>i.amount+' '+i.unit+' '+i.name).join('. '));return c==='repeat step'?'Reading this step.':'Reading ingredients.'}
 if(c.startsWith('open ')||c.startsWith('cook ')){const name=c.replace(/^(open|cook) /,'');const meal=day.rows.find(m=>m.slot.toLowerCase()===name);const matches=recipes.filter(r=>r.name.toLowerCase()===name||r.id===name);const r=meal?.recipe??(matches.length===1?matches[0]:undefined);if(r){open(r,'cook');return 'Opened '+r.name;}return 'No exact match. Say the dish name shown in the collection or “cook breakfast”.'}
 setSelected(null);go('assistant');void conversation.send(command);return 'Opening your conversation…';
 }});
 const list=recipes.filter(r=>(mealFilter==='All'||r.slot===mealFilter)&&r.name.toLowerCase().includes(search.toLowerCase()));
 const blocked=saving||!ready;
 const dateControl=<div className="date-control"><Button variant="ghost" aria-label="Previous day" disabled={!date} onClick={()=>setDate(addDays(dayDate,-1))}><ChevronLeft/></Button><Input aria-label="Menu date" type="date" value={dayDate} min="2026-09-15" max={addDays(todayIST(),365)} onChange={e=>e.target.value&&setDate(e.target.value)}/><Button variant="ghost" aria-label="Next day" onClick={()=>setDate(addDays(dayDate,1))}><ChevronRight/></Button></div>;
 function mealCards(){return <div className="meal-grid">{day.rows.map((m,i)=>{const r=m.recipe,key=dayDate+'|'+m.slot,locked=kitchen.locks.includes(key);return <article className={'meal-card tone-'+i} key={m.slot}><div className="meal-top"><span className="meal-label">{i===0?<Sun size={18}/>:i===3?<Moon size={18}/>:<Utensils size={18}/>} {m.slot}</span>{r&&<Button variant="ghost" className="icon-button" title={locked?'Unlock meal':'Lock this meal'} aria-label={locked?'Unlock '+m.slot:'Lock '+m.slot} disabled={blocked} onClick={()=>save({type:'lock',date:dayDate,slot:m.slot,recipeId:r.id,locked:!locked})}>{locked?<LockKeyhole size={17}/>:<LockKeyholeOpen size={17}/>}</Button>}</div><button className="meal-title" onClick={()=>r&&open(r)} disabled={!r}>{r?.name??'Choose a suitable dish'}</button><p className="meal-description">{r?.ingredients.slice(0,3).map(i=>i.name).join(' · ')}</p><div className="meal-meta"><span><Clock size={14}/>{r?.time??'—'} min</span><span>{locked?'Locked':m.overridden?'Your choice':frequencyLabel(m.frequency)}</span></div><div className="meal-actions"><Button disabled={!r} onClick={()=>r&&open(r,'cook')}><ChefHat size={16}/>Cook</Button><Button variant="ghost" disabled={blocked||locked} onClick={()=>setSwap(m.slot)}><RefreshCw size={15}/>Change</Button></div></article>})}</div>}
 function recipeCards(mode:'recipe'|'cook'|'family'='recipe',items=list){return <div className="recipe-grid">{items.map((r,i)=><article className={'recipe-card tone-'+i%4} key={r.id}><div className="recipe-card-top"><span className="eyebrow">{r.slot}</span><Button variant="ghost" className="icon-button" aria-label={(kitchen.favourites.includes(r.id)?'Remove favourite ':'Favourite ')+r.name} disabled={blocked} onClick={()=>flag('favourite',r.id,!kitchen.favourites.includes(r.id))}><Heart size={18} fill={kitchen.favourites.includes(r.id)?'currentColor':'none'}/></Button></div><button className="recipe-name" onClick={()=>open(r,mode)}>{r.name}</button><p>{r.ingredients.slice(0,3).map(i=>i.name).join(' · ')}</p><span className="frequency-badge">{frequencyLabel(rules[r.id]?.kind)}</span><div className="recipe-bottom"><span><Clock size={14}/>{r.time} min</span><Button variant="ghost" onClick={()=>open(r,mode)}>{mode==='cook'?'Start cooking':mode==='family'?'Cook for everyone':'Open recipe'}<ArrowRight size={16}/></Button></div>{view==='favourites'&&<Button className="lock-favourite" disabled={blocked||r.allergens.some(a=>profile.allergies.includes(a))} onClick={()=>save({type:'lock',date:dayDate,slot:r.slot,recipeId:r.id,locked:true})}><LockKeyhole size={15}/>Lock for {nice(dayDate)}</Button>}</article>)}</div>}
 return <><SideNav view={view} go={go} name={profile.name}/><SidebarInset className={"kid-inset "+(view==='home'?'home-screen':'')}><header className="topbar"><div className="topbar-left"><SidebarTrigger/>{(depth>0||view!=='home')&&<Button variant="ghost" aria-label="Go back" onClick={back}><ChevronLeft size={19}/>Back</Button>}<span>{nav.find(n=>n.id===view)?.name}</span></div><button className="baby-pill" onClick={()=>go('profile')}><span className="baby-initial">{profile.name.slice(0,1)}</span><span>{profile.name}<small>{Math.max(0,months)} months old</small></span></button></header><main className="main-content">{view!=='home'&&<div className="page-heading"><div><p className="eyebrow">YOUR LITTLE ONE’S KITCHEN</p><h1>{headings[view][0]}</h1><p>{headings[view][1]}</p></div>{['home','week','shopping','prep','busy','favourites'].includes(view)&&dateControl}</div>}
 {error&&<div className="message error" role="alert">{error}<Button variant="ghost" onClick={load}>Retry loading</Button></div>}{notice&&<div className="message success" role="status"><Check size={18}/>{notice}</div>}{ready&&!selected&&editing===undefined&&!swap&&!removing&&!openMobile&&voicePanel}
 {!ready?<section className="panel empty"><ChefHat size={30}/><h2>{error?'Your planner is unavailable':'Getting your kitchen ready…'}</h2><p>{error?'Please retry to load your saved choices.':'Your meals and preferences will appear here.'}</p></section>:<>
 {view==='home'&&<><div className="day-toolbar"><div className="day-toggle"><Button variant={dayDate===todayIST()?'default':'ghost'} aria-pressed={dayDate===todayIST()} onClick={()=>setDate(todayIST())}>Today</Button><Button variant={dayDate===tomorrow?'default':'ghost'} aria-pressed={dayDate===tomorrow} onClick={()=>setDate(tomorrow)}>Tomorrow</Button></div><div className="compact-date"><Input aria-label="Menu date" type="date" value={dayDate} max={addDays(todayIST(),365)} onChange={e=>e.target.value&&setDate(e.target.value)}/></div></div><h1 className="sr-only">Daily menu</h1><div className="home-layout"><section>{day.rows.length?mealCards():<div className="panel">This planner starts at 12 months. Check the birth date in My baby.</div>}<section className="sides-panel"><div className="section-heading"><h2>Sides &amp; snacks</h2><span className="count-pill">Swipe to explore →</span></div><p className="muted">Serve alongside meals or at the snack time shown. Ingredients are included in your shopping list and reminder.</p><div className="sides-carousel" role="region" aria-label="Sides and snacks carousel" tabIndex={0}>{day.additions.map((a,i)=><article className={'meal-card side-card tone-'+i%4} key={a.name}><div className="meal-top"><span className="meal-label"><Leaf size={18}/>{a.meal}</span><span className="count-pill">{i+1} / {day.additions.length}</span></div><h3 className="meal-title">{a.name}</h3><div className="side-amounts">{a.ingredients.map(ingredient=><p key={ingredient.name}><b>{amount(ingredient.amount)} {ingredient.unit}</b> {ingredient.name}</p>)}</div><h4>How to serve</h4><p>{a.prep}</p><small>Prepare this amount; offer a small portion first and more if hungry.</small></article>)}</div><p className="small-note">{day.texture} Continue usual breastfeeding or your agreed milk plan; offer water with meals.</p></section></section><aside className="home-aside"><section className="night-card"><span className="round-icon"><Moon/></span><p className="eyebrow">PREPARE TONIGHT</p><h2>{pendingTomorrow.length?`${pendingTomorrow.length} little jobs for tomorrow`:'Tomorrow is looking easy'}</h2>{pendingTomorrow.slice(0,3).map(t=><p className="prep-preview" key={t.id}><Check size={16}/>{t.title}</p>)}{!pendingTomorrow.length&&<p>No advance-preparation tasks left for tomorrow’s menu.</p>}<Button onClick={()=>go('prep')}>Open preparation list<ArrowRight size={16}/></Button></section><button className="shopping-shortcut" onClick={()=>go('shopping')}><ShoppingBasket/><span><b>Buy this week</b><small>{shopping.filter(i=>!kitchen.pantry.includes(i.name)).length} ingredient lines to check</small></span><ArrowRight size={18}/></button><div className="food-photo"><img src="./idli.jpg" alt="Idli with sambar and chutney on a family table"/><div><b>Familiar food.<br/>A little extra care.</b><button onClick={()=>go('family')}>Make a family meal <ArrowRight size={15}/></button></div></div></aside></div></>}
 {view==='week'&&<><div className="section-heading"><h2>{nice(dayDate)} – {nice(addDays(dayDate,6))}</h2><Button variant="outline" onClick={()=>go('shopping')}><ShoppingBasket size={16}/>Shopping list</Button></div><div className="week-grid">{Array.from({length:7},(_,i)=>balancedDay(addDays(dayDate,i),profile,overrides,rules,recipes)).map((d,i)=><article className={'week-card tone-'+i%4} key={d.date}><button onClick={()=>{setDate(d.date);go('home')}}><h3>{nice(d.date)}</h3><ArrowRight size={16}/></button>{d.rows.map(m=><div key={m.slot}><span>{m.slot}</span><button onClick={()=>m.recipe&&open(m.recipe)}>{m.recipe?.name??'No suitable dish'}{kitchen.locks.includes(d.date+'|'+m.slot)&&<LockKeyhole size={13}/>}</button></div>)}</article>)}</div><section className="panel"><h2>A look at the balance</h2><p className="muted">Food-group presence across these seven days, reflecting your changes.</p><div className="coverage-grid">{reviewWeek(dayDate,profile,overrides,rules,recipes).map(c=><div key={c.label}><b>{c.days}<small>/7</small></b><span>{c.label}</span></div>)}</div><p className="small-note">These counts do not measure portions eaten or guarantee every nutrient requirement. Discuss growth, milk, vitamin D and iron with your paediatrician when needed.</p></section></>}
 {['recipes','family','cook'].includes(view)&&<>{view==='recipes'&&<><div className="feature-toolbar"><Button onClick={()=>go('dishes')}>Add a list of dishes</Button><Button variant="outline" onClick={()=>{setEditorName('');setEditing(null)}}>Write a recipe</Button><span>{recipes.length} dishes in full collection</span></div><details className="panel"><summary>Recipe research & removed dishes</summary><p>Traditional bases with baby adaptations, not a claim that every recipe is uniquely Tamil or medically reviewed. Open a dish to see its source where available. The collection includes baby adaptations and home-style variations.</p><p><a href="https://gkfooddiary.com/homemade-baby-food-recipes-easy-indian/" target="_blank" rel="noreferrer">GKFoodDiary recipe collection</a> · <a href="https://www.sharmispassions.com/porridge-recipes-for-babies/" target="_blank" rel="noreferrer">Sharmis Passions porridge collection</a></p><p>Some source pages recommend sweeteners or make health claims; these are not adopted here. Preparation follows <a href="https://www.cdc.gov/infant-toddler-nutrition/foods-and-drinks/choking-hazards.html">CDC choking guidance</a>.</p>{data.removed.map(r=><div className="locked-row" key={r.id}><b>{r.name}</b><Button disabled={blocked} onClick={()=>save({type:'recipeRemove',recipeId:r.id,removed:false})}>Restore</Button></div>)}</details></>}{view==='recipes'&&<div className="info-banner"><CalendarDays size={20}/><p>Open any recipe to set how often it appears: weekly, every two weeks, monthly or regular rotation.</p></div>}{view==='family'&&<div className="info-banner"><Users size={20}/><p>Choose your family dish. See when to set aside the baby portion and how to finish each plate.</p></div>}{view==='cook'&&<div className="info-banner"><Volume2 size={20}/><p>Large step-by-step instructions in English. Read-aloud uses your device’s available English voice.</p></div>}<div className="meal-filters">{['All','Breakfast','Lunch','Snack','Dinner'].map(m=><Button key={m} variant={mealFilter===m?'default':'outline'} onClick={()=>setMealFilter(m)}>{m} ({m==='All'?recipes.length:recipes.filter(r=>r.slot===m).length})</Button>)}</div><div className="searchbar"><Search size={18}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a recipe, e.g. idli or pongal" aria-label="Search recipes"/></div>{recipeCards(view==='family'?'family':view==='cook'?'cook':'recipe')}{!list.length&&<div className="panel empty"><h2>No matching recipe yet</h2><p>Add your family recipe with ingredients and steps using “Add a dish”. A dish name alone does not generate a verified recipe.</p></div>}</>}
 {view==='pantry'&&<><div className="feature-toolbar"><span className="count-pill">{kitchen.pantry.length} ingredients checked</span><Button disabled={blocked||!kitchen.pantry.length} onClick={async()=>{if(await save({type:'plan',date:dayDate,mode:'pantry'}))go('home')}}><PackageCheck size={17}/>Plan {nice(dayDate)} with these</Button></div><div className="info-banner"><PackageCheck size={20}/><p>Check ingredients you have enough of for the planned week. Quantities are not tracked or deducted automatically; recheck these when the menu changes.</p></div><div className="searchbar"><Search size={18}/><Input value={stockSearch} onChange={e=>setStockSearch(e.target.value)} placeholder="Search ingredients" aria-label="Search pantry ingredients"/></div><div className="pantry-grid">{ingredientNames.filter(n=>n.toLowerCase().includes(stockSearch.toLowerCase())).map(n=><label className={'pantry-item '+(kitchen.pantry.includes(n)?'checked':'')} key={n}><Checkbox checked={kitchen.pantry.includes(n)} disabled={blocked} onCheckedChange={v=>flag('pantry',n,!!v)}/><span>{n}</span></label>)}</div><section className="panel"><h2>Closest matches in your kitchen</h2><p className="muted">Missing ingredients stay visible. Allergens and meal-frequency choices still apply when planning.</p><div className="matches">{recipes.filter(r=>!r.allergens.some(a=>profile.allergies.includes(a))).map(r=>({r,s:stockMatch(r,kitchen.pantry)})).sort((a,b)=>b.s.have/b.s.total-a.s.have/a.s.total).slice(0,4).map(({r,s})=><button key={r.id} onClick={()=>open(r)}><b>{r.name}</b><span>{s.have}/{s.total} ingredients available</span><small>{s.missing.length?'Still need: '+s.missing.join(', '):'All ingredients checked'}</small></button>)}</div></section></>}
 {view==='shopping'&&<><div className="feature-toolbar"><div><b>{nice(dayDate)} – {nice(addDays(dayDate,6))}</b><p className="muted">Baby batches for 7 days, including balancing sides.</p></div><Button variant="outline" onClick={()=>setMissingOnly(!missingOnly)}>{missingOnly?'Show all ingredients':'Show only missing'}</Button></div><div className="info-banner"><ShoppingBasket size={20}/><p>Tick “Have enough” to remove an ingredient from the missing list. This also updates My pantry. Keep different units separate; check your supplies against the full quantities.</p></div><section className="panel shopping-panel">{shopping.filter(i=>!missingOnly||!kitchen.pantry.includes(i.name)).map(i=><label className="shopping-row" key={i.name+i.unit}><Checkbox checked={kitchen.pantry.includes(i.name)} disabled={blocked} onCheckedChange={v=>flag('pantry',i.name,!!v)} aria-label={'Have enough '+i.name}/><span><b>{i.name}</b><small>Have enough</small></span><strong>{amount(i.amount)} {i.unit}</strong></label>)}{shopping.every(i=>kitchen.pantry.includes(i.name))&&missingOnly&&<div className="empty"><PackageCheck size={34}/><h2>Everything is checked</h2><p>You’ve marked all ingredients as available. Check freshness and quantities before cooking.</p><Button variant="outline" onClick={()=>setMissingOnly(false)}>Review all ingredients</Button></div>}</section></>}
 {view==='prep'&&<><div className="feature-toolbar"><span className="count-pill">For {nice(dayDate)}</span><span className="reminder-chip"><Bell size={16}/>6 PM IST · Phone reminder</span></div><section className="panel prep-panel">{prepTasks(day.rows).map(t=>{const done=kitchen.prepDone.includes(dayDate+'|'+t.id);return <label className={'prep-task '+(done?'done':'')} key={t.id}><Checkbox checked={done} disabled={blocked} onCheckedChange={v=>flag('prep',dayDate+'|'+t.id,!!v)}/><span><b>{t.title}</b><p>{t.detail}</p></span></label>})}{!prepTasks(day.rows).length&&<div className="empty"><Check size={32}/><h2>No advance prep needed</h2><p>Check the ingredients, then follow the cooking steps when it’s time.</p></div>}</section><div className="info-banner"><Bell size={20}/><p>Your evening phone notification uses the saved menu on this device. Check this preparation list for the latest completion status; changes after a reminder appear here immediately.</p></div><p className="small-note"><a href="https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/big-thaw-safe-defrosting-methods" target="_blank" rel="noreferrer">Safe thawing guidance</a></p></>}
 {view==='busy'&&<><div className="busy-banner"><span className="round-icon"><Zap/></span><div><h2>Make {nice(dayDate)} a little easier</h2><p>Choose dishes with cooking times of 20 minutes or less where possible. Keep locked and specifically scheduled meals, plus the balancing sides.</p></div><Button disabled={blocked} onClick={async()=>{if(await save({type:'plan',date:dayDate,mode:'busy'}))go('home')}}>Use quick meals<ArrowRight size={16}/></Button></div><section className="panel"><h2>Your suggested swaps</h2>{day.rows.map(m=>{const id=suggestDay(dayDate,profile,overrides,rules,kitchen,'busy',recipes)[m.slot];const r=recipes.find(r=>r.id===id)??m.recipe;return <div className="swap-preview" key={m.slot}><span>{m.slot}</span><div><b>{r?.name??'No suitable dish'}</b><small>{id?'Replaces '+m.recipe?.name:'Kept as planned'} · {r?.time??'—'} min</small>{r&&<small>{stockMatch(r,kitchen.pantry).missing.length?'Check: '+stockMatch(r,kitchen.pantry).missing.join(', '):'Ingredients checked in pantry'}</small>}</div></div>})}<p className="small-note">Cooking times exclude advance preparation. Dosa and idli need ready fermented batter. A locked or scheduled dish may take longer.</p></section></>}
 {view==='favourites'&&<><div className="info-banner"><LockKeyhole size={20}/><p>Lock a favourite for the selected date. Busy-day and pantry changes leave locked meals alone. Unlock it from its meal card to change it.</p></div>{recipeCards('recipe',recipes.filter(r=>kitchen.favourites.includes(r.id)))}{!kitchen.favourites.length&&<div className="panel empty"><Heart size={32}/><h2>Your favourites belong here</h2><p>Tap the heart on any recipe to save it.</p><Button onClick={()=>go('recipes')}>Browse recipes</Button></div>}<section className="panel"><h2>Upcoming locked meals</h2>{kitchen.locks.filter(k=>k.slice(0,10)>=todayIST()).sort().map(key=>{const [d,slot]=key.split('|');const r=recipes.find(r=>r.id===overrides[key]);return <div className="locked-row" key={key}><LockKeyhole size={17}/><span><b>{r?.name??'Saved meal'}</b><small>{nice(d)} · {slot}</small></span><Button variant="outline" disabled={blocked||!r} onClick={()=>r&&save({type:'lock',date:d,slot,recipeId:r.id,locked:false})}>Unlock</Button></div>})}{!kitchen.locks.some(k=>k.slice(0,10)>=todayIST())&&<p className="muted">No upcoming meals are locked.</p>}</section></>}
 {view==='assistant'&&conversation.panel}{view==='dishes'&&<DishList names={data.dishNames??[]} recipes={recipes} rules={rules} busy={blocked} save={save} open={open} add={name=>{setEditorName(name);setEditing(null)}}/>}{view==='phone'&&<PhoneSettings reload={load}/>}{view==='profile'&&<section className="panel profile-form">{!data.onboarded&&<div className="info-banner"><p>Welcome! Enter your baby’s name and birth date to start the meal plan. You can change these anytime.</p></div>}<label htmlFor="baby-name">Baby’s name</label><Input id="baby-name" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><label htmlFor="baby-dob">Date of birth</label><Input id="baby-dob" type="date" max={todayIST()} value={!data.onboarded&&draft.dob===todayIST()?'':draft.dob} onChange={e=>setDraft({...draft,dob:e.target.value})}/><h2>Known allergen exclusions</h2><p className="muted">Check all ingredients and packaged foods. This list is not exhaustive.</p><div className="allergen-options">{allergens.map(a=><label key={a}><Checkbox checked={draft.allergies.includes(a)} onCheckedChange={v=>setDraft({...draft,allergies:v?[...draft.allergies,a]:draft.allergies.filter(x=>x!==a)})}/>{a}</label>)}</div><Button disabled={blocked} onClick={()=>save({type:'profile',profile:draft})}>Save details</Button><p className="small-note">Textures update with age, but follow eating skills. Feed seated upright with supervision. Avoid whole nuts, whole beans, hard raw vegetables, bones and whole peppercorns.</p></section>}
 </>}
 <footer><span>Traditional Tamil food. English instructions. Made for little eaters.</span><details><summary>Food guidance & photo credit</summary><p>Recipes are baby-adapted starting points, not personalised nutritional prescriptions. <a href="https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding">WHO feeding guidance</a> · <a href="https://www.cdc.gov/infant-toddler-nutrition/foods-and-drinks/choking-hazards.html">Choking prevention</a></p><p>Photo: <a href="https://commons.wikimedia.org/wiki/File:IDLI_SAMBAR_AND_CHUTNEY_04.jpg">Bajrang01 / Wikimedia Commons</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>, cropped. Family serving shown.</p></details></footer></main></SidebarInset>
 <Dialog open={!!selected} onOpenChange={o=>{if(!o){stopVoice();setSelected(null)}}}><DialogContent floating={selected?voicePanel:undefined} className={'recipe-dialog has-floating '+(detailMode==='cook'?'cooking-dialog':'')}><Button variant="ghost" onClick={()=>{stopVoice();setSelected(null)}}><ChevronLeft/>Back</Button><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{detailMode==='cook'?'Cooking view · English':detailMode==='family'?'One shared base, two ways to finish':'Baby-adapted Tamil home cooking · 12 months+'}</DialogDescription>{selected&&<><div className="dialog-tools"><Button variant={detailMode==='recipe'?'default':'outline'} onClick={()=>{stopVoice();setDetailMode('recipe')}}><BookOpen size={16}/>Recipe</Button><Button variant={detailMode==='cook'?'default':'outline'} onClick={()=>setDetailMode('cook')}><ChefHat size={16}/>Cook</Button><Button variant={detailMode==='family'?'default':'outline'} onClick={()=>{stopVoice();setDetailMode('family')}}><Users size={16}/>Family</Button><Button variant="ghost" aria-label="Toggle favourite" disabled={blocked} onClick={()=>flag('favourite',selected.id,!kitchen.favourites.includes(selected.id))}><Heart size={19} fill={kitchen.favourites.includes(selected.id)?'currentColor':'none'}/></Button></div>
 {error&&<p role="alert" className="message error">{error}</p>}{notice&&<p role="status" className="message success">{notice}</p>}
 {detailMode==='recipe'&&<><div className="dialog-tools"><Button variant="outline" onClick={()=>{setEditing(selected);setSelected(null)}}>Tweak dish</Button><Button variant="outline" onClick={()=>{setRemoving(selected);setSelected(null)}}>Remove dish</Button></div><p className="small-note">{selected.custom?'Your family version. ':''}{selected.source?<a href={selected.source} target="_blank" rel="noreferrer">Read the recipe source · adapted here for a baby batch</a>:'Home-style adaptation; a specific recipe source has not been verified.'}</p><div className="frequency-form"><label htmlFor="frequency">How often in the menu?</label><NativeSelect id="frequency" value={rules[selected.id]?.kind??'rotation'} disabled={blocked} onChange={e=>save({type:'frequency',recipeId:selected.id,kind:e.target.value})}>{frequencyOptions.map(([v,l])=><NativeSelectOption key={v} value={v}>{l}</NativeSelectOption>)}</NativeSelect><small>Saves automatically. Weekly: Monday–Sunday. Monthly: calendar month. Every two weeks: 14 days from saving.</small></div><h3>Ingredients · baby batch</h3><ul className="recipe-ingredients">{selected.ingredients.map(i=><li key={i.name}><span>{i.name}</span><b>{amount(i.amount)} {i.unit}</b></li>)}</ul><h3>How to cook</h3><ol className="recipe-steps">{selected.steps.map(s=><li key={s}>{s}</li>)}</ol><Button disabled={blocked||selected.allergens.some(a=>profile.allergies.includes(a))} onClick={async()=>{if(await save({type:'lock',date:dayDate,slot:selected.slot,recipeId:selected.id,locked:true})){setSelected(null);go('home')}}}><LockKeyhole size={16}/>Lock for {nice(dayDate)}</Button></>}
 {detailMode==='cook'&&<><div className="cooking-top"><span className="count-pill">Step {step+1} of {selected.steps.length}</span><Button variant="outline" disabled={!voice} onClick={speaking?stopVoice:readAloud}>{speaking?<Square size={16}/>:<Volume2 size={16}/>} {speaking?'Stop reading':'Read steps aloud'}</Button></div>{!voice&&<p className="muted">Read-aloud is unavailable in this browser. You can follow the large written steps.</p>}<div className="cooking-step"><span>{String(step+1).padStart(2,'0')}</span><p>{selected.steps[step]}</p></div><div className="step-actions"><Button variant="outline" disabled={step===0} onClick={()=>setStep(step-1)}><ChevronLeft/>Back</Button><Button onClick={()=>{if(step<selected.steps.length-1)setStep(step+1);else{stopVoice();setSelected(null)}}}>{step===selected.steps.length-1?'Finish cooking':'Next step'}<ChevronRight/></Button></div><details className="cooking-ingredients"><summary>Keep ingredients handy</summary><ul>{selected.ingredients.map(i=><li key={i.name}>{amount(i.amount)} {i.unit} {i.name}</li>)}</ul></details></>}
 {detailMode==='family'&&<><div className="family-intro"><Users size={25}/><p>Use your family’s usual batch size. These steps explain where to separate the baby portion.</p></div>{familyGuide(selected).map((s,i)=><section className="family-step" key={s.title}><span>{i+1}</span><div><h3>{s.title}</h3><p>{s.detail}</p></div></section>)}<Button onClick={()=>setDetailMode('cook')}><ChefHat size={16}/>Open cooking steps</Button></>}
 <p className="safety-note">{selected.note&&selected.note+' '}{texture(months)}{selected.allergens.length>0&&' Allergens: '+selected.allergens.join(', ')+'.'}</p></>}</DialogContent></Dialog>
 {editing!==undefined&&<RecipeEditor initialName={editorName} recipe={editing} busy={saving} onClose={()=>setEditing(undefined)} onSave={async r=>{const ok=await save({type:'recipeSave',recipe:r});return ok}}/>}
 <AlertDialog open={!!removing} onOpenChange={o=>!o&&setRemoving(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove {removing?.name}?</AlertDialogTitle><AlertDialogDescription>This removes the dish from rotation, favourites, frequency settings and saved meal choices, including locks. You can restore the dish later; saved choices are not restored.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep dish</AlertDialogCancel><AlertDialogAction disabled={blocked} onClick={async()=>{if(removing&&await save({type:'recipeRemove',recipeId:removing.id,removed:true}))setRemoving(null)}}>Remove dish</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={!!swap} onOpenChange={o=>!o&&setSwap(null)}><DialogContent className="recipe-dialog"><Button variant="ghost" onClick={()=>setSwap(null)}><ChevronLeft/>Back</Button><DialogTitle>Choose {swap?.toLowerCase()}</DialogTitle><DialogDescription>For {nice(dayDate)}. Showing dishes assigned to this meal. See Recipe collection for every dish. A manual choice can exceed a frequency limit.</DialogDescription>{error&&<p className="message error" role="alert">{error}</p>}<div className="swap-list">{recipes.filter(r=>r.slot===swap&&!r.allergens.some(a=>profile.allergies.includes(a))).map(r=><Button variant="outline" key={r.id} disabled={blocked} onClick={async()=>{if(await save({type:'override',date:dayDate,slot:swap,recipeId:r.id}))setSwap(null)}}>{r.name}<span>{r.time} min</span></Button>)}</div><Button variant="secondary" disabled={blocked} onClick={async()=>{if(await save({type:'override',date:dayDate,slot:swap,recipeId:null}))setSwap(null)}}>Restore automatic choice</Button></DialogContent></Dialog>
 </>;
}
